## docker-compose BareOS Director/Storage/Client/webUI and MySQL Database
version: '3'
services:
  kong:
    image: kong:latest
    volumes:
      - ./kong-vol:/usr/local/kong/declarative
    environment:
     - KONG_DATABASE=off
     - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
     - 8000:8000
     - 8443:8443
     - 8001:8001
     - 8444:8444
  apisix:
    image: iresty/apisix
    # build:
    #   context: ./..
    #   dockerfile: alpine/Dockerfile
    restart: always
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    network_mode: host

  etcd:
    # if you are in the mainland China, please use Azure China mirror:
    # image: gcr.azk8s.cn/etcd-development/etcd:v3.3.12
    image: gcr.io/etcd-development/etcd:v3.3.12
    command: /usr/local/bin/etcd --advertise-client-urls http://0.0.0.0:2379 --listen-client-urls http://0.0.0.0:2379
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
    ports:
      - "127.0.0.1:2379:2379/tcp"
    # networks:
    #   - apisix
  kong-gui:
    image: pgbi/kong-dashboard
    command: 
      - start
      - --kong-url
      - http://kong:8001
    depends_on:
      - kong
    ports:
     - 8090:8080
    # -p 8080:8080  

  hello1:
    container_name: hello1
    image: nginxdemos/hello
    # networks:
    #   - kong

  hello2:
    container_name: hello2
    image: nginxdemos/hello
    # networks:
      # - kong

# networks:
#     external:
#         # use the bridge driver, but enable IPv6
#         driver: bridge        
#     kong:
        # use the bridge driver, but enable IPv6
        # driver: bridge        


