## docker-compose BareOS Director/Storage/Client/webUI and MySQL Database
version: '3'
services:
  kong:
    image: kong:latest
    volumes:
      - ./kong-vol:/usr/local/kong/declarative
    environment:
     - KONG_DATABASE=off
     - KONG_DECLARATIVE_CONFIG=/usr/local/kong/declarative/kong.yml
     - KONG_PROXY_ACCESS_LOG=/dev/stdout
     - KONG_ADMIN_ACCESS_LOG=/dev/stdout
     - KONG_PROXY_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_ERROR_LOG=/dev/stderr
     - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
     - 8000:8000
     - 8443:8443
     - 8001:8001
     - 8444:8444

  hello1:
    container_name: hello1
    image: nginxdemos/hello
    # networks:
    #   - kong

  hello2:
    container_name: hello2
    image: nginxdemos/hello
    # networks:
      # - kong

# networks:
#     external:
#         # use the bridge driver, but enable IPv6
#         driver: bridge        
#     kong:
        # use the bridge driver, but enable IPv6
        # driver: bridge        



     
     

#   bareos-sd:
#     image: harbor.v2.rancher.geohub.space/i3s/bareos/bareos-storage:1.0
#     ports:
#       - 9103:9103
#     volumes:
#       - /home/bareos/config/storage:/etc/bareos
#       - /home/bareos/data/storage:/var/lib/bareos/storage
#     environment:
#       - BAREOS_SD_PASSWORD=ThisIsMySecretSDp4ssw0rd

#   bareos-fd:
#     image: harbor.v2.rancher.geohub.space/i3s/bareos/bareos-client:1.0
#     volumes:
#       - /home/bareos/config/client:/etc/bareos
#       - /home/bareos/data/director:/var/lib/bareos-director #(required for MyCatalog backup)
#     environment:
#       - BAREOS_FD_PASSWORD=ThisIsMySecretFDp4ssw0rd

#   bareos-webui:
#     image: harbor.v2.rancher.geohub.space/i3s/bareos/bareos-webui:1.0
#     ports:
#       - 8889:80
#     environment:
#       - BAREOS_DIR_HOST=bareos-dir
#     volumes:
#       - /home/bareos/config/webui:/etc/bareos-webui

#   bareos-db:
#     image: mysql:5.6
#     volumes:
#       - /home/mysql/data:/var/lib/mysql
#     environment:
#       - MYSQL_ROOT_PASSWORD=ThisIsMySecretDBp4ssw0rd

#   #bareos-db:
#   #  image: postgres:9.3
#   #  volumes:
#   #    - /home/pgsql/data:/var/lib/postgresql/data
#   #  environment:
#   #    - POSTGRES_PASSWORD=ThisIsMySecretDBp4ssw0rd

#   smtpd:
#     image: namshi/smtp
# #EOF
